# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6f:f4:77:a9:55:99:f0:ed:02:89:0f:ec:d7:e7:24:ef"
      - run:
          name: Avoid hosts unknown for github
          command: echo -e “Host github.com\n\tStrictHostKeyChecking no\n” > ~/.ssh/config

      - run:
          name: Clone GitHub repository
          command: git clone -b 'rule-evaluator-core-1.0.0'  --single-branch https://github.com/dfpaulino/ruleEvaluatorService.git --depth=1
      # Download and cache dependencies
      - run:
          name: cd into directory
          working_directory: ~/repo/ruleEvaluatorService
          command: mvn install -DskipTests

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install -DskipTests
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean