version: "3.9"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    networks:
      - resnet

  res_jpa:
    image: dpaulino/rule-evaluator:${RES_VERSION}
    ports:
      - "8080:8080"
    environment:
            SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:mysql://mysql:3306/test","spring.datasource.username":"test","spring.datasource.password":"test","spring.jpa.hibernate.ddl-auto":"none","spring.jpa.show-sql":"false","logging.level.org.farmtec.res.service":"INFO"}'
    depends_on:
      - mysql
    networks:
      - resnet

networks:
  resnet:
    driver: bridge
